apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Create a Subscription in Azure
  annotations:
    github.com/project-slug: ${{ values.owner }}/${{ values.repo }}
    techdocs.io/website: https://${{ values.owner }}.github.io/${{ values.repo }}
    backstage.io/techdocs-ref: dir:.
    github.com/team-slug: backstage/platform engineering
    tags:
    - azure
    - resource  
    - terraform
    - cd
spec:
  type: resource
  owner: group:platform-team
  lifecycle: development
  system: azure
